"""empty message

Revision ID: 4a6c1ac5150e
Revises: fb3704c4e468
Create Date: 2023-08-07 10:28:11.997827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6c1ac5150e'
down_revision = 'fb3704c4e468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint('email_constraint', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('email_constraints', type_='unique')
        batch_op.drop_column('email')
    
    # ### end Alembic commands ###
